title: Lee Robin Clarke #>p style = "font-family: Times New Roman">
logo: "/images/WIN_20220201_12_05_29_Pro.jpg?raw=true" # your photo (or logo) here


description: > # your text below (remove <br> elements if you don't need line breaks)
  I have a bachelor's degree in Environmental Science and Management with an emphasis in Education and Interpretation and a
  master's degree in Geography and Environmental Sustainability with an emphasis in Geospatial Technologies.
  I am a graphic designer at heart, and use this as an approach to my cartographic work. 
  I am an avid user of R, mostly deliniating biomes with raster data. 
  I currently work in forestry.
  
   
  
  
  
  <br><br>
 
  <br><br>
  <a href="https://www.linkedin.com/in/lee-clarke-1b2095218/">View My LinkedIn Profile</a> 
 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
